package com.pablo.tests;

import com.pablo.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Condition.*;
import static com.codeborne.selenide.Selectors.byText;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class EpamTests extends TestBase {
    @Test
    @DisplayName("Russian language test")
    void ruLanguageTest() {
        step("open https://www.epam.com/", () -> {
            open("https://www.epam.com/");
        });

        step("click SELECT A LANGUAGE", () -> {
            $(".location-selector__button").click();
        });

        step("click \"СНГ\"", () -> {
            $(".location-selector__panel").$(byText("СНГ")).click();
        });

        step("verify language", () -> {
            $(".layout-box").shouldHave(text("Присоединяйтесь к глобальной команде профессионалов"));
        });
    }

    @Test
    @DisplayName("Poland language test")
    void plLanguageTest() {
        step("open https://www.epam.com/", () -> {
            open("https://www.epam.com/");
        });

        step("click SELECT A LANGUAGE", () -> {
            $(".location-selector__button").click();
        });

        step("click \"PL\"", () -> {
            $(".location-selector__panel").$(byText("Polska")).click();
        });

        step("verify language", () -> {
            $(".header__content").shouldHave(text("Polska"));
        });
    }

    @Test
    @DisplayName("German language test")
    void deLanguageTest() {
        step("open https://www.epam.com/", () -> {
            open("https://www.epam.com/");
        });

        step("click SELECT A LANGUAGE", () -> {
            $(".location-selector__button").click();
        });

        step("click \"DACH\"", () -> {
            $(".location-selector__panel").$(byText("DACH")).click();
        });

        step("verify language", () -> {
            $(".header__content").shouldHave(text("DACH"));
        });
    }

    @Test
    @DisplayName("Switching to tabs test")
    void switchingTest() {
        step("open https://www.epam.com/", () -> {
            open("https://www.epam.com/");
        });

        step("click ow We Do It", () -> {
            $(".header__content").$(byText("How We Do It")).click();
        });

        step("verify text", () -> {
            $(".title").shouldHave(text("How We Do It"));
        });
    }

    @Test
    @DisplayName("Search test")
    void searchTest() {
        step("open https://www.epam.com/", () -> {
            open("https://www.epam.com/");
        });

        step("click search", () -> {
            $(".header-search__button").click();
        });

        step("set value", () -> {
            $("#new_form_search").setValue("Contact").pressEnter();
        });

        step("verify results", () -> {
            $(".search-results__items").shouldHave(text("Contact"));
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.epam.com/'", () ->
            open("https://www.epam.com/"));

        step("Page title should have text 'EPAM | Enterprise Software Development, Design & Consulting'", () -> {
            String expectedTitle = "EPAM | Enterprise Software Development, Design & Consulting";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.epam.com/'", () ->
            open("https://www.epam.com/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}